export enum InjectionToken {
  USER_COMMAND_REPOSITORY = 'USER_COMMAND_REPOSITORY',
  USER_QUERY_REPOSITORY = 'USER_QUERY_REPOSITORY',
  POST_COMMAND_REPOSITORY = 'POST_COMMAND_REPOSITORY',
  POST_QUERY_REPOSITORY = 'POST_QUERY_REPOSITORY',
}
